Repository GSG-G10/divano, pull requests merged in 2021-10, with the labels that each got.

#20 create file structure for server side
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
  server/app.js
  server/controllers/index.js
  server/database/config/build.js
  server/database/config/build.sql
  server/database/config/fakedata.sql
  server/database/connection/index.js
  server/database/queries/cart/index.js
  server/database/queries/index.js
  server/database/queries/products/index.js
  server/database/queries/users/index.js
  server/index.js
  server/middlewares/index.js
  server/routes/index.js
  server/test/index.test.js
  server/utils/validations/index.js
Labels: Awaiting Review

#2 file structure
  README.md
  client/.eslintrc.json
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/index.css
  client/src/index.js
Labels: Changes Requested

#28 create get user query and add user query
  server/database/queries/users/addUser.js
  server/database/queries/users/getUser.js
  server/database/queries/users/index.js
Labels: Awaiting Review

#26 23 cart queries
  server/database/config/build.sql
  server/database/queries/cart/addToCart.js
  server/database/queries/cart/deleteFromCart.js
  server/database/queries/cart/getItems.js
  server/database/queries/cart/index.js
  server/database/queries/cart/updateQuentity.js
Labels: Awaiting Review

#33 getProductsQuery
  server/database/queries/products/index.js
Labels: Awaiting Review

#36 create hash password and compare password functions
  server/controllers/auth/hashPassword.js
Labels: Awaiting Review

#31 insert fake data #30
  package-lock.json
  server/database/config/fakedata.sql
Labels: Awaiting Review

#38 Authentication Middleware
  server/middlewares/authentication.js
  server/middlewares/index.js
Labels: Awaiting Review

#42 39 logout route
  server/controllers/index.js
  server/controllers/logout.js
  server/routes/index.js
Labels: Awaiting Review, back-end

#40 login controller
  server/app.js
  server/controllers/auth/createSession.js
  server/controllers/auth/index.js
  server/controllers/auth/login.js
  server/controllers/auth/logout.js
  server/controllers/index.js
  server/database/queries/cart/index.js
  server/database/queries/index.js
  server/database/queries/users/addUser.js
  server/database/queries/users/getUser.js
  server/routes/index.js
Labels: Awaiting Review, back-end

#51 handling the server error #44
  server/controllers/errors/404Error.js
  server/controllers/errors/index.js
  server/controllers/errors/serverError.js
  server/routes/index.js
Labels: Awaiting Review, back-end

#55 53 product details route
  server/controllers/index.js
  server/controllers/productDetails.js
  server/database/queries/products/getProductDetails.js
  server/database/queries/products/index.js
  server/routes/index.js
Labels: Awaiting Review, back-end

#43 create login validation middleware
  server/controllers/auth/createSession.js
  server/controllers/auth/hashPassword.js
  server/controllers/auth/index.js
  server/controllers/auth/login.js
  server/database/queries/users/getUser.js
  server/middlewares/index.js
  server/utils/validations/index.js
  server/utils/validations/loginSchema.js
Labels: Changes Requested, back-end

#45 create sign up router
  server/app.js
  server/controllers/auth/signup.js
  server/controllers/index.js
  server/database/queries/users/addUser.js
  server/middlewares/index.js
  server/middlewares/signupValidation.js
  server/routes/cart.js
  server/routes/signup.js
  server/utils/validations/signUpSchema.js
Labels: Awaiting Review

#47 cart router
  server/controllers/index.js
  server/controllers/pages/cart.js
  server/controllers/pages/index.js
  server/database/config/build.js
  server/database/connection/index.js
  server/database/queries/cart/getItems.js
  server/middlewares/authentication.js
  server/middlewares/index.js
  server/routes/index.js
Labels: Awaiting Review

#52 Product route
  client/.gitignore
  server/controllers/getProducts.js
  server/controllers/index.js
  server/database/queries/products/index.js
Labels: Awaiting Review

#57 3 main header component
  client/src/App.js
  client/src/assets/banner.jpg
  client/src/components/mainpage/MainHeader.js
  client/src/components/mainpage/NavBar.js
  client/src/components/mainpage/Style.css
Labels: Awaiting Review, front-end

#56 exports and requires edits
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/index.js
  server/controllers/auth/index.js
  server/controllers/index.js
  server/middlewares/index.js
  server/routes/cart.js
  server/routes/index.js
  server/routes/signup.js
Labels: Awaiting Review

#64 make some edits to the navbar #3
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/public/sofa-icon-circle.png
  client/src/App.js
  client/src/components/common/NavBar/NavBar.js
  client/src/components/common/NavBar/Style.css
  client/src/components/mainpage/MainHeader.js
  client/src/components/mainpage/Style.css
Labels: Awaiting Review, front-end

#58 8 signup com
  client/package-lock.json
  client/src/App.css
  client/src/App.js
  client/src/antd/dist/antd.css
  client/src/components/Common/Button.js
  client/src/components/Common/Input.js
  client/src/components/Signup.js
Labels: Awaiting Review

#68 Add to cart
  README.md
  client/src/App.css
  client/src/App.js
  client/src/functions/addToCart.js
  server/controllers/addtocart.js
  server/database/queries/cart/addToCart.js
  server/database/queries/cart/deleteFromCart.js
  server/database/queries/cart/getItems.js
  server/database/queries/cart/getsingleItem.js
  server/database/queries/cart/index.js
  server/database/queries/cart/updateQuentity.js
  server/database/queries/index.js
  server/routes/index.js
Labels: Awaiting Review

#77 create furniture page #10
  client/src/App.js
  client/src/components/common/productCard/card.js
  client/src/components/mainpage/Style.css
  client/src/pages/Furniture.js
  client/src/pages/cart/cart.js
Labels: Awaiting Review, front-end

#72 fix problems
  client/.eslintrc.js
  client/.eslintrc.json
  client/src/App.css
  client/src/App.js
  client/src/components/Common/Button.js
  client/src/components/Common/Input.js
  client/src/components/Login.js
  client/src/components/Signup.js
  client/src/components/common/NavBar/NavBar.js
  client/src/components/common/NavBar/Style.css
  client/src/components/common/productCard/card.js
  client/src/functions/addToCart.js
  client/src/pages/cart/cart.js
  server/controllers/auth/createSession.js
  server/controllers/auth/logout.js
  server/middlewares/authentication.js
Labels: Awaiting Review
